name: Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check Swift version
      run: |
        swift --version
        
    - name: Build binary
      run: |
        swift build -c release
        
    - name: Verify binary
      run: |
        ls -la .build/release/asbmutil
        .build/release/asbmutil --help
        
    - name: Generate version number
      id: version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        else
          VERSION=$(date +'%Y.%m.%d')-$(echo ${{ github.sha }} | cut -c1-7)
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Generated version: $VERSION"
        
    - name: Create release zip
      run: |
        zip -j asbmutil-${{ steps.version.outputs.version }}.zip .build/release/asbmutil
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: asbmutil-${{ steps.version.outputs.version }}
        path: |
          .build/release/asbmutil
          asbmutil-${{ steps.version.outputs.version }}.zip
        
    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: asbmutil-${{ steps.version.outputs.version }}.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
